### ISSUE TITLE
Built-in `hasFile` check

### ISSUE THREAD

**Issue by IKatsuba** [commonalityco/commonality#200]
I want to check that some files exist for every package and do not want to create specific checks for that. `hasFile` sounds as solution here

**Comment by alec-chernicki** [comment]
This is a great idea! 

I figure that more folks will have ideas for these foundational-level checks that they'd like to see Commonality directly provide and support. I'm going to close out this issue but I've created a discussion so more folks can chime in, feel free to join! 
https://github.com/commonalityco/commonality/discussions/209
