### ISSUE TITLE
Rules with the same names are expanded and collapsed not one at a time, but all at once.

### ISSUE THREAD

**Issue by IKatsuba** [commonalityco/commonality#202]
I created the `hasFile` check.

```typescript
const hasFile = defineCheck((file: string) => {
  return {
    name: 'hasFile',
    message: `Missing ${file}`,
    validate: (ctx) => text(ctx.package.path, file).exists(),
    level: 'error',
  };
});
```

And use it several times. When I click on check detail, all checks with the same names expand or collapse.

<img width="541" alt="image" src="https://github.com/commonalityco/commonality/assets/10637135/f4de6d80-15b1-40a5-aec7-a5c6a6f382d5">

**Comment by alec-chernicki** [comment]
Thanks for the issue! While fixing this issue, I noticed a couple other bugs and have added test coverage to these components. Should be fixed in https://github.com/commonalityco/commonality/pull/207 and is in the latest version of `commonality.
