### ISSUE TITLE
Support monorepos without `package.json`

### ISSUE THREAD

**Issue by IKatsuba** [commonalityco/commonality#203]
Some monorepos are controlled using Nx. They may contain many libraries and applications, but package.json may be the only one in the root. Are there plans to support such monoreps?

**Comment by alec-chernicki** [comment]
The short answer is yes but after a couple more core features are rolled out.

I'm going to close out this issue but I've created a discussion about this topic, feel free to chime in! 
https://github.com/commonalityco/commonality/discussions/208
