### ISSUE TITLE
What's the recommended way of handling CLI telemetry in CI?

### ISSUE THREAD

**Issue by pawelblaszczyk5** [commonalityco/commonality#345]
Hello,
I'm using commonality (it's awesome, thank you very much) and running constrain verification and checks in CI through GitHub Actions. I didn't even notice, but it started [silently failing](https://github.com/pawelblaszczyk5/pawelblaszczyk.dev/actions/runs/8163589958/job/22317173613) some time ago, due to the telemetry addition. 

![image](https://github.com/commonalityco/commonality/assets/54995479/23d0ade4-4a7b-4e89-88d7-33d391f5eb51)

I'm using something similar to the way, that's currently recommended in [docs](https://docs.commonality.co/continuous-integration/github-actions). 

Maybe it'd be nice to update the documentation to warn about it? Currently, I've opted into running `pnpm commonality telemetry enable` before constrain/checks. Is that the best way? I've also looked into the code and saw that there's a env variable that I can also set.  Is telemetry in CI beneficial for you? Because I personally don't mind it in my open source project. 

Thank you in advance!

**Comment by alec-chernicki** [comment]
Telemetry has been removed in commonality@0.2.60 so you shouldn't be receiving this message in CI anymore, let me know if everything looks good on your end! closing now but I'll re-open if things are still an issue.
